# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
