# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0004_auto_20190407_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_name',
        ),
    ]
