# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0005_auto_20190407_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='taskname',
        ),
    ]
