# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0006_auto_20190407_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
