# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0007_remove_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
