# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0009_auto_20190407_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
